Feature/implementing simple jwt
slevvvvin/Django pull request #13
Opened 2021-01-14 15:15 UTC by slevvvvin

2021-01-14 20:22 UTC, TinaArts requested changes
More needed changes in MS Teams

2021-01-14 20:22 UTC, TinaArts commented on blog/api/urls.py
> +from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
Read about best practices for imports

2021-01-15 14:30 UTC, slevvvvin commented on blog/api/urls.py
> +from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
done

2021-01-25 11:34 UTC, TinaArts approved these changes

2021-01-25 11:41 UTC, merged